spring.application.name=api-gateway

server.port=${PORT:8080}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[1].id=resume-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://RESUME-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/resumes/**

spring.cloud.gateway.server.webflux.routes[2].id=ranking-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://RANKING-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/ranking/**

spring.cloud.gateway.server.webflux.routes[3].id=auth-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[0]=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[1]=https://resume-ranking-frontend-kohf.onrender.com
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true


eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90